### ISSUE TITLE
Mapping on Mac

### ISSUE THREAD

**Issue by eric-bixby** [somini/vim-autoclose#1]
When used on a mac, a space is being incorrectly mapped as "^] ".

**Comment by somini** [comment]
What vim version are you using? 
I think it has something to do with commit 3b21a4d. You can test this by reverting that commit and check if it works.

**Comment by eric-bixby** [comment]
I'm using:
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Apr  5 2016 14:53:37)

You are correct.  Reverting that commit fixed the problem.

Thanks!

**Comment by eric-bixby** [comment]
By the way, on my PC/Linux platform, I happen to be using 7.4 (which works).

I assumed this was a platform issue, but do you think this is a VIM version
issue?

**Comment by eric-bixby** [comment]
I was able to install VIM 7.4 on my Mac (using "brew install vim").  The
latest version of vim-autoclose works.
Therefore, the problem does appear to be VIM version related.

**Comment by somini** [comment]
Glad you found the problem! It was a version issue since that mapping was related to abbreviations, nothing to do with Linux-specific code. OSX has a really old vim version by default.
Yeah, we can define the mapping depending on the VIM version. I'll try to fix this today or this weekend.

**Comment by somini** [comment]
I think this fixes it, can you please test it on VIM 7.3? I tried and failed to get that version installed on Linux Mint.

**Comment by eric-bixby** [comment]
Still fails for me in VIM 7.3.  It might be your check for ":abbreviate";
this has existed since VIM 6.0.  You most likely need a more explicit
version check.

**Comment by somini** [comment]
I just pushed a new version, check for v7.04

It might work before, but this should do for now.

**Comment by eric-bixby** [comment]
Yes, that fixed it.  Thanks
